# Generated by Django 5.0.6 on 2024-06-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty', models.IntegerField()),
                ('display', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(default=None, max_length=100)),
                ('chip', models.CharField(default=None, max_length=100)),
                ('camera', models.CharField(default=None, max_length=100)),
                ('camera_recording', models.CharField(default=None, max_length=100)),
                ('operating_system', models.CharField(default=None, max_length=100)),
                ('availability', models.CharField(choices=[('In stock', 'In stock'), ('Out stock', 'Out stock')], max_length=70)),
                ('look_desc', models.TextField()),
                ('look_img', models.ImageField(upload_to='pics')),
                ('touch_desc', models.TextField()),
                ('touch_img', models.ImageField(upload_to='pics')),
                ('cameras_desc', models.TextField()),
                ('cameras_img', models.ImageField(upload_to='pics')),
                ('technology_desc', models.TextField()),
                ('technology_img', models.ImageField(upload_to='pics')),
                ('design_desc', models.TextField()),
                ('design_img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=None, max_length=255, unique=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ecom.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media/')),
                ('off', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('short_desc', models.CharField(max_length=100)),
                ('trending_items', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.category')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ecom.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusive', models.BooleanField(default=False)),
                ('first_exclusive', models.BooleanField(default=False)),
                ('crousel', models.BooleanField(default=False)),
                ('first_crousel', models.BooleanField(default=False)),
                ('first_one', models.BooleanField(default=False)),
                ('frist_exclusel', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product')),
            ],
        ),
    ]
