# Generated by Django 5.0.6 on 2024-06-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0002_rename_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='first_one',
        ),
        migrations.AddField(
            model_name='product',
            name='first_one',
            field=models.BooleanField(default=False),
        ),
    ]
