# Generated by Django 5.0.6 on 2024-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0003_remove_promotions_first_one_product_first_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
