# Generated by Django 5.0.6 on 2024-06-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0009_carousel_second_crousel_carousel_third_crousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotions',
        ),
    ]
