# Generated by Django 5.0.6 on 2024-06-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0010_delete_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.BooleanField(default=False)),
                ('second', models.BooleanField(default=False)),
                ('three', models.BooleanField(default=False)),
                ('four', models.BooleanField(default=False)),
                ('five', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.product')),
            ],
        ),
    ]
