# Generated by Django 5.0.6 on 2024-07-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0015_user_card_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
